### ISSUE TITLE
Syntax error in string replace method

### ISSUE THREAD

**Issue by mitelg** [MalteJanz/ludtwig#91] opened 2024-02-09 09:15 UTC
Following snippet gives a syntax error

```
{% block page_content_section_sidebar %}
    {% set layout = section.sizingMode ? section.sizingMode|replace({_: '-'}) : "container" %}
{% endblock %}
```

I guess the underscore is somehow treated as a special character

**Comment by MalteJanz** [comment] 2024-02-09 10:47
Works fine with ludtwig `0.8.1` and should be a duplicate of https://github.com/MalteJanz/ludtwig/issues/82

**Closed by MalteJanz** 2024-02-09 10:47 UTC
